### ISSUE TITLE
Recoloring System - Remaining TODO for finishing

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#450]
### TODO:
- [ ] Stock recolorable fairings -- fairing tip is not recolored.  might just be bad normals, but appears to truly lack coloring.
  * This is actually caused by bad normals and/or tangents in the stock mesh generation.  The nose bit is recolored, but it is much darker than the rest of the fairing.  
  * Will be fixed in KSP 1.4 (supposedly)
- [ ] SC-MCB-A/B - Need masks/patches/texture-sets created.
- [ ] SLS Mount - Mask does not match NRM.
- [ ] Finish up / export masked emissive shader.  Mostly just need distinct spec channel.
- [ ] DOS modules need a second pass -- some things need to be excluded from recoloring (engine exhaust shields)
- [ ] SRB-US - Textures/masks need finished.  Might need to mirror some UVs.
  - [ ] Stripes A
  - [ ] Stripes B
- [ ] SRB-US - Nozzles need re-export to fix tangents/seams (SRB-G nozzle at least)
- [ ] SC-E-FS/X - WR/L -  ER/L - WT
  - [ ] Mask(s)
  - [ ] Diff rework
  - [ ] Spec rework
  - [ ] Additional NRMs 
  - [ ] Texture set configs
  - [ ] Part config adjustments
  - [ ] Re-add 'lost' texture sets

**Comment by taterkerman** [comment]
Grab a tank. Change the nose. Look at adapter selected vs what is shown, too:
4-3 short uses 4-3-long, and vice versa.

Actually, 3-4 long is NOT screwed up as a texture! The MODEL used is 3-4short. The 3-4 short is using the long model. What I thought was a texture screwup is the short adapter spaced out from the tank.

**Comment by shadowmage45** [comment]
Hehe, nice, I must have fubard some of the model defs when I was bashing around the configs.

**Comment by shadowmage45** [comment]
Ahh, looking into this, apparently I have a second (and third!) file full of adapters that have not been touched/updated for the new system at all; so their texture set defs are all pointing to missing textures, and have invalid set names.

This includes any of the adapters that were added during the StationCore work (Hubs, extended adapters, a few others), as well as any of the 'inverted' adapters (1-2, 3-4, 1-3, etc).

Will work on getting those configs updated today.

**Comment by blowfishpro** [comment]
The max length on the modular upper stage (particularly common bulkhead variant) seems much smaller than before.

I do see the difficulty in having a model look good and support that amount of scaling.  Maybe like the normal tank it should start with multiple length models and then support scaling for fine-tuning.

**Comment by shadowmage45** [comment]
Good catch; it probably is a bit shorter at max... I changed how the scaling was calculated a bit, did not pay any attention to what the previous max was.

But either way, yes, the reason why there is a limit is because of texture stretching.  Even the current limits are way beyond what I would personally like to see (I want zero texture stretching), and about the only way I would feel good with even longer tanks.... is if the base model was longer to begin with.

The good news is that the new MUS code fully supports swapping of upper/lower tank models for ones with longer length.  The bad news is that I won't have time to make new models for them for at least a few days/weeks.  I suppose though, that if the scaling is limited that the existing MFT-C tank models would probably be usable for the purpose (erm...except for their flag decals...).
