### ISSUE TITLE
Unity Standard Shader / PBR Textures - Progress Tracking

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#590]
## Recoloring Part Conversion
- [ ] Stock recolorable fairings -- fairing tip is not recolored.  might just be bad normals, but appears to truly lack coloring.
  * This is actually caused by bad normals and/or tangents in the stock mesh generation.  The nose bit is recolored, but it is much darker than the rest of the fairing.  
  * Will be fixed in KSP 1.4 (supposedly)
- [ ] SC-E (all parts, all steps)
  - [ ] Convert to recolorable textures w/several masks
  - [ ] Add high-res PBR texture set
  - [ ] PBR recoloring conversion patches

## Done and Verified
- [x] MFT-LV
- [x] IPA - FairingBase portion needs recoloring support
- [x] DECOUPLER/PROBECORE
- [x] MSRB-Nozzles-US
- [x] MFT-MOUNT
- [x] ST-GEN-DSP-DOS
- [x] FAIRING BASE
- [x] ST-DOS
- [x] MCB-A/B
- [x] FAIRING PANEL
- [x] SC-A (Soyuz)
- [x] SC-C (Orion)
- [x] MFT-A/B/C/CF/D/S/SF
- [x] MFT-ADPT
- [x] MFT End-Cap
- [x] MUS-Body
- [x] MSRB-Body
- [x] MSRB-Nozzles
- [x] ST-CFG
- [x] ST-COS
- [x] ST-HAB
- [x] SC-B (Apollo)
- [x] SC-V (VA)
- [x] ST-HUB-COS
- [x] ST-HUB-DOS
- [x] ST-GEN-DSP-BKT

## High-Res PBR Textures - Initial Testing Parts:
* SC-ENG-F1 - WIP
* SC-ENG-J-2 - WIP
* SC-B-CM - **DONE**
* SC-B-SM - WIP
* SC-B-BPC - Use PBR based recolorable setup
* MFT-LV - WIP
