### ISSUE TITLE
0.7.39.147 - Progress Tracking

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#624]
## DONE
- [x] FIX - Antenna controls on DOS modules should now be labeled with 'Antenna' suffix.
- [x] CHANGE - Add MJ support to PPC
- [x] CHANGE - Add recoloring support to ISDC engines #625 
- [x] CHANGE - Add MODEL_DATA support to ISDC for rocket selection -- only to options are currently available; more may be added in the future
- [x] FIX - VolumeContainer update problems #626
- [x] CHANGE - Remove KIS integration entirely.  No more KIS storage space in MFT tanks, no more KIS-module-not-found spam in logs.  No more broken Seat0 inventory in pods. 
- [x] CHANGE - IPA-N/W - Now able to be closed after being deployed.
- [x] FIX - Improperly located colliders on Petal Adapter and NodeFairing parts when colliders were enabled on the panels.
- [x] FIX - Petal Adapter/NodeFairing colliders that would be generated, but not parented to anything (and left floating in space).
- [x] CHANGE - Update CRP to v.8.0.0.0
- [x] CHANGE - Add 'ModularRCS' module to all stand-alone RCS parts.  They can now switch between MP and Hypergolic fuel selections in the editor, as well as having a small selection of  built-in structural standoffs.
- [x] UPDATE - Add more RCS structural stand-off options
- [x] CHANGE - MUS now uses ModuleRCSFX for its RCS module.
- [x] NEW PART - PC-DRC - Data Return Capsule (dev/prototype part)
- [x] NEW PART - PC-SRF - Robotic Surface Sample Drill (dev/prototype part)
- [x] NEW PART - ModularServiceModule (dev/prototype part)
- [x] FIX - Add PBR-Highres enabling patch on SC-B-CMX
- [x] FIX - RealPlume configs for LMAE + LMDE engines
- [x] CHANGE - Add 'resource units' display to SSTUInflatable module
- [x] CHANGE - Move Fairing parts (upgrade/unlocks) to construction/composites line of tech-nodes
- [x] FIX - Add placeholder IVAs to parts currently lacking them #637
- [x] FIX - Some minor description errors in SC-V configs
- [x] FIX - PBR-highres texture sets for MFT-LV fuel tanks having improper metallic values (shader-side problem fixed in TU)
- [x] UPDATE - Add PBR texture support for SC-ENG-MOUNT-FLAT
- [x] UPDATE - Add PBR texture support for SC-TANK-MOUNT-NONE
- [x] FIX - Incorrect texture-set definitions for MUS-intertank model.
- [x] FIX- PBR texture support for MUS-intertank
- [x] UPDATE - Add recoloring support for ST-MST model (multi-axis solar panel base)
- [x] UPDATE - Add pbr-recoloring support for ST-MST
