### ISSUE TITLE
0.7.39.149 - Progress Tracking

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#650]
# Progress Tracking for Release 0.7.39.149
* ETA - 12/31/17 (no guarantee)
* It is possible that some items on this list will get pushed to future releases, it is only a rough outline of plans.
* Items may be added/removed arbitrarily.  If you want to make sure something gets addressed, open an issue ticket on it (if one does not already exist).

## TODO
- [x] FIX - #651 - Make sure recoloring GUI config works for adjusting GUI size.
- [ ] FIX - #644 - Adjust modular parachute deployment safety speed/pressure for parts with parachutes that lack drogues.
- [ ] CHANGE - Adjust drogue parachute safety speed/pressure for increased tolerance at lower altitudes/higher density.
- [ ] CHANGE - Add angle adjustment to the SSTUModularRCS standoff structure, and attach node(s)
- [ ] CHANGE - Adjust SSTUModularRCS standoff selection - 
  * remove the tank and i-beam models
  * add more truss models
  * fill in the removed A/B/C/? selections
- [ ] MODELING+TEXTURES - SC-B-CM - PBR texture - fix under-cap NRM details; triangulation is all wrong, causing major distortion.  Apparently SP is winding the quads differently than Unity.
- [ ] CONFIGS+TEXTURES - PAR models have odd MET texture/mask/recoloring capability
- [ ] UNITY+CONFIGS - Flag decal mesh in tanks/etc needs to use a different shader.  It looks like it uses an unlit shader at some angles/lighting setups.
- [ ] SC-A-DM -- needs slightly higher max deploy speed/pressure for drogues; it is possible to exceed their max velocity when below ~12k, resulting in parachutes refusing to open
- [ ] UNITY - FIX - Re-export HUB models with decals set to Icon_Hidden
  - [ ] Should also fix the shader used by decals -- will need to be adjusted in model texture sets...

## Pushed To Future Releases:
