### ISSUE TITLE
KSP-1.4.X - 'Rework' Update - Progress Tracking

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/SSTULabs#701]
# Parts
### Pods - need window textures fixed for proper PBR setup
* For some reason, the conversion to DDS kills specular reflections
- [ ] SSTU/Parts/LanderCore/LC2-POD/SSTU-LC2-POD
- [ ] SSTU/Parts/LanderCore/LC3-POD/SSTU_LanderCore_LC3-POD
- [ ] SSTU/Parts/LanderCore/LC5-POD/SSTU_LanderCore_LC5-POD
- [ ] SSTU/Parts/ShipCore/Series-A/SC-A-DM/SSTU-SC-A-DM
- [ ] SSTU/Parts/ShipCore/Series-A/SC-A-OM/SSTU-SC-A-OM
- [ ] SSTU/Parts/ShipCore/Series-B/SC-B-CM/SSTU-SC-B-CM
- [ ] SSTU/Parts/ShipCore/Series-B/SC-B-CMX/SSTU-SC-B-CMX
- [ ] SSTU/Parts/ShipCore/Series-C/SC-C-CM/SSTU-SC-C-CM
- [ ] SSTU/Parts/ShipCore/Series-C/SC-C-CMX/SSTU-SC-C-CMX
- [ ] SSTU/Parts/ShipCore/Series-V/SC-V-CM/SSTU-SC-V-CM

### Engine-equipped parts - need thrust and resource/volume scale adjustments
- [ ] SSTU/Parts/Engine/SRB/SC-ENG-SRB-A/SSTU-SC-ENG-SRB-A
- [ ] SSTU/Parts/Engine/SRB/SC-ENG-SRB-U/SSTU-SC-ENG-SRB-U
- [ ] SSTU/Parts/General/InterstageDecoupler/SC-GEN-ISDC/SSTU-SC-GEN-ISDC
- [ ] SSTU/Parts/General/RadialBoosterDecoupler/SC-GEN-RBDC/SSTU-SC-GEN-RBDC
- [ ] SSTU/Parts/General/RCS/SSTU-GEN-MRCS/SSTU-GEN/MRCS

### Balance/Scaling adjustments
- [x] SSTU/Parts/General/ModularHeatShield/SC-GEN-MHS/SSTU-SC-GEN-MHS
  * Allow specification of 'square' scaling (rather than cubic), for mass and resource volume

### Misc Part fixes and updates
- [ ] SC-Pod parts / SM's have incorrect cost - likely need to add 'subtractCost = false' to VC module configs.
- [ ] SSTU/Parts/Tanks/SSTU-TANK-MFT-D/SSTU-TANK-MFT-D
- [x] SSTU/Parts/Tanks/SSTU-TANK-MFT-R/SSTU-TANK-MFT-R
  * Need converted to new ModularPart
  * Model defs need updated and made conformal
- [ ] SSTU/Parts/Tanks/SSTU-TANK-MUS/SSTU-TANK-MUS
  * RCS support - model defs with position specs, parent slot specs
  * Solar support - either removed, or solar position data added to tank/intertank/mount defs used on the part.
- [ ] SSTU/Parts/Bays/SSTU-MCB-A/SSTU-MCB-A
  * Needs Airstream shield added + tested/validated
    * Needs to shield entire part, not just fairing-covered portion.

----

# PartModules / Code
### VolumeContainer
- [ ] Move OnGUI code out of class, use the same singleton/separate object based system the other GUIs are using.

### AnimationModule - Features
- [ ] Clean up handling of switching models mid-animation... persist animation state and make sure to set new animation state (time, speed)

### SolarModule - Features
- [ ] Support for disabling of tracking
- [ ] Clean up handling when switching; dump old tranform data, set new transforms to existing state

### TexturesUnlimited Integration
- [ ] Clean up part icons under openGL on windows - invert Y axis
  * Needs to be applied to -all- parts.
  * May require multiple shader variants, to better handle the various base shaders
  * Should somehow normalize color/albedo between stock, masked, pbr, and pbr-masked shaders
    * Decrease brightness of PBR texture inputs
    * Apply AO mask texture to base diffuse color
- [x] Finalize the DX11 'fix', update GFX-API check
- [ ] Adjust recoloring GUI default height?
- [ ] Add secondary set of default colors for PBR recoloring use?
